User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 600
LogFile "/dev/stderr"
PidFile "/tmp/tinyproxy.pid"
MaxClients 20
Allow 0.0.0.0/0
ConnectPort 443
Filter "/etc/tinyproxy/model.filter"
FilterDefaultDeny Yes
